### ISSUE TITLE
Table Tool not closing

### ISSUE THREAD

**Issue by pascalheidman-bedarf** [jakob/TableTool#36] opened 2017-06-19 16:04 UTC
When I exit the tool by menu it still runs. Only force closing works in this situation. Happens every time.

**Comment by jakob** [comment] 2017-06-20 08:03
This issue could be caused by an exception that happens while closing open documents. We need more information to debug.

Can you see if any messages related to Table Tool appear in Console.app when you try to quit the application?

Could it be that this only happens with certain documents? If that is the case, could you share a copy of a problematic documents with us? Of course, only if the document doesn't contain private data.

**Comment by fulldecent** [comment] 2018-07-05 20:13
Closing because the issue is not reproducible. @pascalheidman-bedarf if you are still around please send details and we can reopen the issue.

**Closed by fulldecent** 2018-07-05 20:13 UTC
