### ISSUE TITLE
Leading Zero Removed From 12+Long Text Fields

### ISSUE THREAD

**Issue by SemperAndroid** [jakob/TableTool#41] opened 2017-07-25 17:14 UTC
PROBLEM:
Given the following data saved as a UTF-8 CSV.  It always imports the upc number with 11 chars and not the leading zero.

upc, sku
012345678901, ABCDEF

DESIRED BEHAVIOR:
Data is imported with the leading zero present.

[Sample.xlsx](https://github.com/jakob/TableTool/files/1174219/Sample.xlsx)

**Comment by andidhouse** [comment] 2017-08-16 09:57
Exactly - a csv tool needs to keep all numbers including the 0 or more then one in the beginning.
We have the same problem here and this is a great tool - but deleting the "0"(s) at the beginning makes this tool not usable in our case. Or is there a setting we did not see somewhere?

**Comment by jlgeering** [comment] 2017-08-23 05:50
same issue here...

how about adding an option to disable the "autodetect data type" feature on opening a file ?

**Comment by tibtiiiiib** [comment] 2017-10-20 09:27
Same issue here
Opening a CSV file shouldn't change its format at all.
Made the software useless for me but great job anyway, thank you a lot

**Comment by mcdado** [comment] 2017-11-11 11:37
Postcodes in Italy are five digit numbers, in the Rome area they start with zero. It's always a pain with Excel that tries to be smart and convert those fields to numbers. You either have to set the format of the cell as "00000", format as text, or use `'` notation.

Please leave the data as it is, or if anything please add an option to do so.

**Comment by fulldecent** [comment] 2018-07-05 20:14
Closing as duplicate of #9

**Closed by fulldecent** 2018-07-05 20:14 UTC
